version: '3.4'

services:
  test-api:
    container_name: "TestApi"
    build:
      context: .
      dockerfile: TestTaskApi/Dockerfile
    ports:
      - "8080:80"
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
    networks: 
      - database_network
  
  
  database:
    container_name: "MySql"
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=superstrongPASSword"
    networks:
      - database_network
      
      
networks:
  database_network:
    external: false